
name: Android Testers CI - Deployment to Firebase
# Triggered every time master branch has a push.
on:
  push:
    branches: main

    workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      # Checkout Repo
      - name: Checkout Repo
        uses: actions/checkout@v1

      # Setting up Java 1.8
      - name: Setting Java JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      # Building debug apk
      - name: Building Debug Apk
        run: ./gradlew assembleDebug --stacktrace

      # Deployment
      - name: Deploy artifact to Firebase
        uses: wzieba/Firebase-Distribution-Github-Action@v1.2.1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          token: ${{secrets.FIREBASE_CI_TOKEN}}
          groups: Testers
          file: app/build/outputs/apk/debug/app-debug.apk
